Cypress.Commands.add('login', () => {
  cy.visit('/login')
  cy.get('#email').type(Cypress.env('user_email'))
  cy.get('#password').type(Cypress.env('user_password'), { log: false })
  cy.contains('button', 'Login').click()
})

Cypress.Commands.add('fillCreditCardForm', () => {
  cy.get('#storage').type('1')
  cy.get('#name').type('Mary Doe')
  cy.iframe('[title="Secure card payment input frame"]')
    .as('iframe')
    .find('[name="cardnumber"]')
    .type('4242424242424242')
  cy.get('@iframe')
    .find('[name="exp-date"]')
    .type('1222')
  cy.get('@iframe')
    .find('[name="cvc"]')
    .type('123')
  cy.get('@iframe')
    .find('[name="postal"]')
    .type('12345')
  cy.contains('button', 'Purchase').click()
})
